# Generated by Django 5.2.3 on 2025-07-06 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brand_logo_store_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='parent_lists', through='api.ListItem', to='api.item')),
            ],
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.list'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_inviter', to=settings.AUTH_USER_MODEL)),
                ('joined_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.list')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='members',
            field=models.ManyToManyField(related_name='joined_lists', through='api.Membership', through_fields=('joined_list', 'member'), to=settings.AUTH_USER_MODEL),
        ),
    ]
