# Generated by Django 5.2.3 on 2025-07-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_list_listitem_list_membership_list_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='PLACEHOLDER', max_length=35),
            preserve_default=False,
        ),
    ]
